[package]
name = "aoc-2017"
version = "0.1.0"
edition = "2021"

[lib]
name = "aoc_2017"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc = { path = "../aoc" }
